#######################################################################
###                                                                 ###
###                 Fix hyprland.conf monitor config                ###
###                                                                 ###
#######################################################################
cecho(){
  RED="\033[1;91m"
  GREEN="\033[1;92m"  
  YELLOW="\033[1;93m" 
  CYAN="\033[1;96m"
	BLUE="\\033[1;94m"
  NC="\033[0m" # No Color

  printf "${!1}${2} ${NC}\n"
}

# Get monitor info
monitor=$(hyprctl monitors list | awk 'NR==1 {print $2}')
res=$(hyprctl monitors list | awk 'NR==2 {print $1}')


echo -ne "Monitor0 is "$monitor" at resolution "$res". \n\n"

while true ; do

read -p "Is this correct? (y/n) " yn

case $yn in 
    [yY] ) cecho "GREEN" "\nProceeding....";
       break;;
    [nN] ) cecho "RED" "\nAborting!\n\n";
       exit;;
    * ) cecho "YELLOW" "\ninvalid response\n\n";;
esac

done

# Make sure file exists
if ! [ -e $HOME/.config/hypr/hyprland.conf ] ; then
  echo -ne "Not here, homeboy! \n"
  exit 1
fi  

# Make a backup copy in case we mess this up 
cp $HOME/.config/hypr/hyprland.conf $HOME/.config/hypr/hyprland.bak

# Change the values 
sed -i "s/autogenerated/# &/g" $HOME/.config/hypr/hyprland.conf
sed -i "s/^monitor=.*$/monitor=$monitor,$res,0x0,1/" $HOME/.config/hypr/hyprland.conf
